### ISSUE TITLE
ninesleep binary panics on incoming network connections

### ISSUE THREAD

**Issue by andrewmv** [bobobo1618/ninesleep#10]
I've successfully jailbroken my pod, then compiled and copied the rust binary to it. It starts and listens for network connections, but when I make any kind of rest call (including just a /hello), the listener thread panics.

```
[2021-03-24T13:09:19Z WARN  rocket::launch] 🚀 Rocket has launched from http://0.0.0.0:8000
[2021-03-24T13:09:29Z INFO  ninesleep] New UNIX socket connection
[2021-03-24T13:09:30Z INFO  ninesleep] Incoming TCP connection
[2021-03-24T13:09:30Z INFO  ninesleep] Session started for device 77202acebd2ddd26fc0a2c703e72490ff84b91f7
[2021-03-24T13:09:37Z INFO  ninesleep] Incoming TCP connection
thread '<unnamed>' panicked at src/main.rs:405:67:
called `Result::unwrap()` on an `Err` value: Semantic(None, "invalid type: bytes, expected map")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1677:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1102:23
   4: ninesleep::handle_data_stream
             at /home/growlph/Code/ninesleep/src/main.rs:405:32
   5: ninesleep::main::{{closure}}::{{closure}}::{{closure}}
             at /home/growlph/Code/ninesleep/src/main.rs:450:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Testing the API call with curl like so:
```
$ curl -v http://192.168.1.50:1337/hello
*   Trying 192.168.1.50:1337...
* Connected to 192.168.1.50 (192.168.1.50) port 1337 (#0)
> GET /hello HTTP/1.1
> Host: 192.168.1.50:1337
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

**Comment by andrewmv** [comment]
Oh! I was using the wrong port - it works correctly on 8000
Not sure what 1337 is for - I found it in the source code because I couldn't figure out what port to use at first, and I'm not very experienced with Rust.
